name: Test and maybe create a new release

on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag_result: ${{ steps.tag.outputs.tag_result }}
      requested_version: ${{ steps.tag.outputs.requested_version }}
      previous_version: ${{ steps.tag.outputs.previous_version }}
    steps:
      - run: sudo apt update && sudo apt install -y git && git --version
      - uses: actions/checkout@v2
        with:
          # We need entire history of tags
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: Run tagging commands
        id: tag
        run: |
          set +e
          go run . tag 1>/tmp/versions.txt

          printf "versions: $(cat /tmp/versions.txt)\n"
          echo "requested_version=$(cut -d',' -f 1 /tmp/versions.txt)" >> $GITHUB_OUTPUT
          echo "previous_version=$(cut -d',' -f 2 /tmp/versions.txt)" >> $GITHUB_OUTPUT

          tag_result="$?"
          echo "tag_result=$tag_result" >> $GITHUB_OUTPUT
          # The range between 8 and 63 inclusive is reserved for custom
          # error codes that contain specific meaning.
          if [ $tag_result -lt 8 -o $tag_result -gt 63 ]; then
            exit $tag_result
          fi
          exit 0
      - name: Push tags
        run: git push origin --tags --force
        if: steps.tag.outputs.tag_result == 0

  release:
    needs: tag
    if: needs.tag.outputs.tag_result == 0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          args: release --clean
          version: "~> v2"
        env:
          GORELEASER_CURRENT_TAG: ${{ needs.tag.outputs.requested_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
